In [1]:
import numpy as np

In [2]:
x = [True, True, True]
y = x + [False]

In [3]:
x.all()

AttributeError: 'list' object has no attribute 'all'

In [4]:
np.all(x)

True

In [6]:
np.all(y)

False

In [8]:
np.where(y==True)

(array([], dtype=int64),)

In [9]:
y==True

False

In [10]:
z = np.array(y)

In [12]:
np.where(z==False)

(array([3]),)

In [14]:
t = np.arange(20)
has_box_been_checked = np.full(len(t), False)

In [15]:
has_box_been_checked

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [19]:
np.where(has_box_been_checked==False)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),)

In [20]:
strings = ['Apara','Dan','Suyog','Zilliam','A rare breed of panda','Rober Steele']

In [21]:
strings.sort()

In [22]:
strings

['A rare breed of panda', 'Apara', 'Dan', 'Rober Steele', 'Suyog', 'Zilliam']

In [23]:
import Levenshtein

In [24]:
Levenshtein.distance(strings[0],strings[1])

17